config/routes.rb
Rails.application.routes.draw do

  resources :line_items do
    member do
      post :show_order_items
    end
  end

  resources :summary, only: %i[show] do
    member do
      post :order_confirmation
    end
  end

  resources :addresses

  resources :carts, controller: 'cart', only: %i[index update edit] do
    member do
      post :add_product
      post :remove_product
      post :add_shipping_type_to
      get :collect
    end
  end

  devise_for :users

  namespace :admin do
    root to: 'products#index'
    resources :categories
    resources :products
    resources :users
    resources :orders, only: %i[index show update]
  end

  root to: 'products#index'

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  resources :categories, only: [:show]
  resources :products, only: %i[index show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :first_name, :last_name, :zip_code, :street, :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def full_price
    unit_price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries
  belongs_to :shipping_type, optional: true
  belongs_to :user, optional: true
  has_many :line_items
  has_many :order_transitions, autosave: false

  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
           to: :state_machine

  def state_machine
    @state_machine ||= OrderStateMachine.new(self, transition_class: OrderTransition)
  end

  def self.transition_class
    OrderTransition
  end

  def self.initial_state
    OrderStateMachine.initial_state
  end

  def self.transition_name
    :transitions
  end

  def full_cost
    cost = line_items.map { |e| e.full_price }.sum
    if shipping_cost
      return cost + shipping_cost
    end 
    cost
  end
end

app/models/order_state_machine.rb
class OrderStateMachine
  include Statesman::Machine

  state :new, initial: true
  state :confirmed
  state :in_progress
  state :shipped
  state :cancelled

  transition from: :new, to: %i[confirmed cancelled]
  transition from: :confirmed, to: %i[in_progress cancelled]
  transition from: :in_progress, to: %i[shipped cancelled]
  transition from: :shipped, to: :cancelled

  after_transition(to: :cancelled) do |order|
    OrderMailer.order_cancelled(order).deliver
  end

  after_transition(to: :confirmed) do |order|
    OrderMailer.order_confirmation(order).deliver
  end

  after_transition(to: :in_progress) do |order|
    OrderMailer.order_in_progress(order).deliver
  end

  after_transition(to: :shipped) do |order|
    OrderMailer.order_shipped(order).deliver
  end

  def self.states_map
    {
      'new' => 'Niepotwierdzone',
      'confirmed' => 'Potwierdzone',
      'in_progress' => 'W realizacji',
      'shipped' => 'Wysłane',
      'cancelled' => 'Anulowne'
    }
  end
end

app/models/order_transition.rb
class OrderTransition < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordTransition

  belongs_to :order, inverse_of: :order_transitions

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = order.order_transitions.order(:sort_key).last
    return unless last_transition.present?
    last_transition.update_column(:most_recent, true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_item

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price, numericality: { greater_than: 0.0 }

  mount_uploader :photo, ProductPhotoUploader
end

app/models/shipping_type.rb
class ShippingType < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_one :address
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @address = Address.create
  end

  def create
    @address = Address.create(address_params)
    if !@address.new_record?
      current_user.update(address: @address)
      redirect_to summary_path(current_user.id), notice: 'Poprawnie zapisano adres'
    else
      render action: :new
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update_attributes(address_params)
      redirect_to summary_path(current_user.id)
    else
      render action: :edit
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :first_name,
      :last_name,
      :city,
      :zip_code,
      :street
    )
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :current_cart, only: 'show'

  def index
    @search = Order.where(user: current_user).search(params[:q])
    @orders = @search.result.page(params[:page]).per(30)
  end

  def collect
    @cart = Order.find(params[:id])
    @shippings = ShippingType.all
  end

  def edit
    @cart = current_cart
  end

  def add_product
    order = current_cart_or_create
    product = Product.find(params[:id])
    if item = order.line_items.where(product: product).first
      item.quantity += 1
      item.save
    else
      order.line_items.create product: product,
      quantity: 1,
      unit_price: product.price,
      unit_name: product.name
    end
    redirect_to :back, notice: "Produkt #{product.name} dodano do koszyka"
  end

  def remove_product
    order = current_cart
    product = Product.find(params[:product_id])
    item = order.line_items.where(product: product).first
    if item
      item.destroy
    end
    redirect_to :back, notice: 'Usunięto produkt z koszyka'
  end

  def add_shipping_type_to
    order = current_cart
    shipping = ShippingType.find(params[:shipping_id])
    order.shipping_type = shipping
    order.shipping_cost = shipping.cost
    order.save
    redirect_to collect_cart_path, notice: 'Dodano rodzaj dostawy'
  end

  private

  def get_order_data
  
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(6)
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def show_order_items
    @order = Order.find(params[:id])
    @line_items = LineItem.where(order: @order)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def show
    @user = User.find(params[:id])
    @order = current_cart
  end

  def order_confirmation
    order = current_cart
    user = current_user
    order.user = user
    order.save
    session.delete(:order_id)
    redirect_to root_path, notice: 'Dziękujemy za złozenie zamówienia !'
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
  def full_name(address)
    names = [address.last_name, address.first_name]
    names.join(' ')
  end

  def city_zipcode(address)
    data = [address.city, address.zip_code]
    data.join(' ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def time_zone(date)
    (date + 2.hours).strftime("%Y-%d-%m %H:%M:%S")
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/summary/show.html.erb
<div class="container">
<h1>Podsumowanie</h1>
  <table class="table table-striped">
    <thead>
      <th>Produkt</th>
      <th>Liczba sztuk</th>
      <th>Cena jednostkowa</th>
      <th>Cena całkowita</th>
    </thead>
    <tbody>
      <%  @order.line_items.each do |item| %>
        <tr>
          <td><%= link_to item.unit_name, product_path(item.product) %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency item.unit_price %></td>
          <td><%= number_to_currency item.full_price %></td>
        </tr>
      <% end %>
       <tr>
        <td><%= @order.shipping_type.name %></td>
        <td></td>
        <td><%= number_to_currency @order.shipping_type.cost %></td>
        <td></td>
      </tr>
    </tbody>
   </table>

<h3>Całkowity koszt zamówienia : <%= number_to_currency @order.full_cost %></h3>

   <p>Adres zamówienia</p>
  <p><%= full_name(@user.address) %></p>
  <p><%= @user.address.street %></p>
  <p><%= city_zipcode(@user.address)%></p>

    <%= link_to order_confirmation_summary_path, method: :post, class: "btn btn-success btn-lg" do%>
        Potwierdź zamówienie
        <span class="fa fa-step-forward"></span>
      <% end %>
  </div>

app/views/summary/show_summary.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <th>Produkt</th>
      <th>Liczba sztuk</th>
      <th>Cena jednostkowa</th>
      <th>Cena całkowita</th>
    </thead>
    <tbody>
      <%  @order.line_items.each do |item| %>
        <tr>
          <td><%= link_to item.unit_name, product_path(item.product) %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency item.unit_price %></td>
          <td><%= number_to_currency item.full_price %></td>
        </tr>
      <% end %>
       <tr>
        <td><%= @order.shipping_type.name %></td>
        <td></td>
        <td><%= number_to_currency @order.shipping_type.cost %></td>
        <td></td>
      </tr>
    </tbody>
   </table>

<h3>Całkowity koszt zamówienia : <%= number_to_currency @order.full_cost %></h3>

   <p>Adres zamówienia</p>
  <p><%= full_name(@user.address) %></p>
  <p><%= @user.address.street %></p>
  <p><%= city_zipcode(@user.address)%></p>
  </div>