config/routes.rb
Rails.application.routes.draw do

  resources :line_items do
    member do
      post :show_order_items
    end
  end

  resources :summary, only: %i[show] do
    member do
      post :order_confirmation
    end
  end

  resources :addresses

  resources :carts, controller: 'cart', only: %i[index update edit] do
    member do
      post :add_product
      post :remove_product
      post :add_shipping_type_to
      get :collect
    end
  end

  devise_for :users

  namespace :admin do
    root to: 'products#index'
    resources :categories
    resources :products
    resources :users
    resources :orders, only: %i[index show update]
  end

  root to: 'products#index'

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  resources :categories, only: [:show]
  resources :products, only: %i[index show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @search = Category.search(params[:q])
    @categories = @search.result
  end

  def new
    @category = Category.create
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'Pomyslnie dodano kategorie'
    else
      render action: :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, notice: 'Pomyslnie zmieniono kategorie'
    else
      render action: :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.products.size.zero?
      @category.destroy
      redirect_to admin_categories_path, notice:
      "Pomyślnie usunięto kategorie #{@category.name}"
    else
      redirect_to admin_categories_path, alert:
      "W #{@category.name} znajdują się produkty, usuń je przed usunięciem kategorii"
    end
  end

  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(6)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
    <%= f.input :name, label: 'Nazwa' %>
    <%= f.submit 'Dadaj kategorie' %>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render "form" %>

app/views/admin/categories/index.html.erb
    <h1>Kategorie</h1>

    <%= link_to new_admin_category_path, class: "btn btn-success" do %>
        <span class="fa fa-plus"></span>Dodaj nową kategorie
    <% end %>

    <hr /> 

    <table class="table table-striped">
        <thead>
            <tr>
                <th><%= sort_link(@search, :name, "Nazwa") %></th>
                <th class ="text-center">Akcje</th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td><%= category.name %></td>
                    <td align="center">
                        <%= link_to "Edycja", edit_admin_category_path(category), class: "btn btn-default btn-xs" %>
                        <%= link_to "Usuń", admin_category_path(category), 
                        method: :delete,
                        data: { confirm: 'Jesteś pewien?'},
                        class: "btn btn-danger btn-xs" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

app/views/admin/categories/new.html.erb
<%= render "form" %>