config/routes.rb
Rails.application.routes.draw do

  resources :line_items do
    member do
      post :show_order_items
    end
  end

  resources :summary, only: %i[show] do
    member do
      post :order_confirmation
    end
  end

  resources :addresses

  resources :carts, controller: 'cart', only: %i[index update edit] do
    member do
      post :add_product
      post :remove_product
      post :add_shipping_type_to
      get :collect
    end
  end

  devise_for :users

  namespace :admin do
    root to: 'products#index'
    resources :categories
    resources :products
    resources :users
    resources :orders, only: %i[index show update]
  end

  root to: 'products#index'

  get 'regulamin', to: 'static#terms', as: :terms
  get 'polityka-prywatnosci', to: 'static#privacy', as: :privacy
  get 'dostawa', to: 'static#shipping', as: :shipping
  get 'o-sklepie', to: 'static#about', as: :about

  resources :categories, only: [:show]
  resources :products, only: %i[index show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_item

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price, numericality: { greater_than: 0.0 }

  mount_uploader :photo, ProductPhotoUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @search = Product.search(params[:q])
    @products = @search.result.page(params[:page]).per(30)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.create
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to admin_products_path, notice: 'Pomyslnie dodano product'
    else
      render action: :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to admin_products_path, notice: 'Pomyslnie zmieniono produkt'
    else
      render action: :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, notice: 'Pomyślnie usunięto produkt'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :category_id,
      :description,
      :long_description,
      :price,
      :photo
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
    <%= f.input :name, label: 'Nazwa' %>
    <%= f.input :description, label: 'Opis' %>
    <%= f.input :long_description,label: 'Szczegółowy opis', :input_html => {:rows => 10} %>
    <%= f.input :price, label: 'Cena'%>
    <%= f.association :category, label: 'Kategoria'%>
    <%=image_tag @product.photo%>
    <%= f.input :photo %>
    <%= f.submit 'Dodaj produkt'%>
<% end %>

app/views/admin/products/edit.html.erb
<%= render "form" %>

app/views/admin/products/index.html.erb
    <h1>Produkty</h1>

    <%= link_to new_admin_product_path, class: "btn btn-success" do %>
        <span class="fa fa-plus"></span>Dodaj nowy Produkt
    <% end %>

    <hr />

    <div class="search-form">
        <%= search_form_for [:admin, @search] do |f| %>
            <%= f.text_field :name_or_category_name_cont, placeholder: "Szukaj Tekstu" %>
            <%= f.text_field :price_gt, placeholder: "Cena od" %>
            <%= f.text_field :price_lt, placeholder: "Cena do"%>
            <%= f.submit "Szukaj", class: "btn btn-info btn-sm"%>
            <%= link_to "Wyczyść filtr", admin_products_path, class:"btn btn-warning btn-sm" %>
        <% end %>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th><%= sort_link(@search, :name, "Nazwa") %></th>
                <th><%= sort_link(@search, :price, "Cena") %></th>
                <th><%= sort_link(@search, :category_name, "Kategoria") %></th>
                <th class ="text-center">Akcje</th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
                <tr>
                    <td><%= product.name %></td>
                    <td><%= number_to_currency product.price %></td>
                    <td><%= product.category.name %></td>
                    <td align="center">
                        <%= link_to "Podgląd", admin_product_path(product), class: "btn btn-primary btn-xs" %>
                        <%= link_to "Edycja", edit_admin_product_path(product), class: "btn btn-default btn-xs" %>
                        <%= link_to "Usuń", admin_product_path(product), 
                        method: :delete,
                        data: { confirm: 'Jesteś pewien?'},
                        class: "btn btn-danger btn-xs" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%=paginate @products %>

app/views/admin/products/new.html.erb
<%= render "form" %>

app/views/admin/products/show.html.erb
<%= render partial: "shared/showProduct" %>